matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - COMPILER_NAME=gcc-7
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11
      - BOOST_VERSION=1.67.0
      - GTEST_VERSION=1.8.1

  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - COMPILER_NAME=gcc-7
      - BUILD_TYPE=Debug
      - CONAN_BUILD_TYPE=Debug
      - COMPILER_LIBCXX=libstdc++11
      - BOOST_VERSION=1.67.0
      - GTEST_VERSION=1.8.1

  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - COMPILER_NAME=gcc-7
      - BUILD_TYPE=Coverage
      - CONAN_BUILD_TYPE=Debug
      - COMPILER_LIBCXX=libstdc++11
      - BOOST_VERSION=1.67.0
      - GTEST_VERSION=1.8.1

  - os: osx
    osx_image: xcode12.2
    language: cpp
    compiler: clang   
    env:
      - COMPILER_NAME=clang-MacOS
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libc++
      - GTEST_VERSION=1.8.1
      - BOOST_VERSION=1.75.0
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
        - /usr/local/Homebrew

install: 
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Coverage ]]; then sudo apt-get install lcov; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install conan; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install conan; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install gnu-sed; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then which sed; fi
  - conan user
  - conan remote add systelab-public https://systelab.jfrog.io/artifactory/api/conan/cpp-conan-production-local
  - conan --version

script:
  - g++ --version
  - mkdir -p build
  - cd build
  - conan install .. -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION}
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make
  - cd bin
  - if [ $TRAVIS_OS_NAME == osx ]; then cp -f *.dylib /usr/local/lib; fi
  - ./TraceAPITest --gtest_output=xml:TraceAPITest.xml
  - cd ..
  - cd test
  - cd TraceAPITest
  - ctest
  - cd ..
  - cd ..
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg ../conanfile.py "TraceAPI/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
    else
      conan export-pkg ../conanfile.py "TraceAPI/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
    fi
  - |
    if [ "$BUILD_TYPE" == "Release" ] || [ "$BUILD_TYPE" == "Debug" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        conan test ../test_package/conanfile.py TraceAPI/${TRAVIS_TAG:1}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
      else
        conan test ../test_package/conanfile.py TraceAPI/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
      fi
    fi
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Coverage ]]; then make TraceAPITestCoverage; fi
  - cd ..

deploy:
  - provider: script
    script: bash ./ci/deploy.sh -v "${TRAVIS_TAG:1}"
    skip_cleanup: true
    on:
      tags: true
      condition: "$BUILD_TYPE != Coverage"
  - provider: script
    script: bash ./ci/build_docs.sh -o "systelab" -s "cpp-trace-api" -t "${TRAVIS_TAG}" -c "Travis" -n "${COMPILER_NAME} ${BUILD_TYPE}" -j "${TRAVIS_JOB_ID}" -p "TraceAPITest"
    skip_cleanup: true
    on:
      tags: true

after_success:
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Coverage ]]; then bash <(curl -s https://codecov.io/bash); fi
