on:
  repository_dispatch:
    types: [doc-build]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    name: 'Automated generation of library documentation'
    steps:
    - name: 'Generate library documentation'
      id: archive-doc
      uses: systelab/cpp-library-doc-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: systelab
        repo-name: cpp-trace-api
        library-name: 'TraceAPI'
        tag-name: ${{ github.event.client_payload.tag }}
        configuration-name: ${{ github.event.client_payload.configuration }}
        ci-system: ${{ github.event.client_payload.ci }}
        job-id: ${{ github.event.client_payload.job }}
